services:
  classifier-app:
    build:
      context: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8001/health'
      interval: 10m
      timeout: 30s
      retries: 3
      start_period: 60s
